### ISSUE TITLE
ReferenceError: Cannot access 'Root' before initialization

### ISSUE THREAD

**Issue by bowis** [ieedan/shadcn-phone-input-svelte#14]

**Comment by ieedan** [comment]
Please provide a reproduction the preview site is absolute proof that it does work

**Comment by Bowis** [comment]
Reproduction: literally when importing it in ANY component. 

`<script lang="ts">
  import PhoneInput from '$lib/components/ui/phone-input/phone-input.svelte';
</script>

<PhoneInput value={'+91 9876543210'} />
`

in `routes/+page.svelte`

**Comment by ieedan** [comment]
Yeah import from the directory not the .svelte file thats why you are having this issue
