### ISSUE TITLE
Doesn't work out the box

### ISSUE THREAD

**Issue by SneakyPanda64** [ieedan/shadcn-phone-input-svelte#9]
Hi, I love the library.

You seem to be importing root in the index.ts which breaks the whole code. I managed to fix it but I thought it would be good idea to it mention.

Also the country icon seems to be cropped
![image](https://github.com/user-attachments/assets/498a26cf-9160-4ea0-b50c-c335d3418852)

**Comment by SneakyPanda64** [comment]
I believe the country icon being cropped could be fixed by removing the "w-4 h-6" on the flag component and the mr-3 in the <span> child

**Comment by ieedan** [comment]
I believe the country uses the same styles as the original but if you found something different you can open a PR. 

As for it not working you can share a repro but the website shows that it does work.
